apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "configmap.fullname" . }}-env"
  labels:
    app: {{ template "configmap.name" . }}
    chart: {{ template "configmap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $setting, $option := .Values.config }}
  {{ $setting }}: "{{ $option }}"
  {{- end }}
